# Copyright 2023 Terramate GmbH
# SPDX-License-Identifier: MPL-2.0

name: benchmarks
on:
  pull_request:
    paths:
      - '**.go'

permissions:
  pull-requests: write

jobs:
  benchmarks:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: run benchcheck
        id: benchmark
        run: |
          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$(make bench/check new=${{ github.event.pull_request.head.sha }})" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: benchmark
          message: |
            ```
            ${{ steps.benchmark.outputs.result }}
            ```
