# Copyright 2023 Terramate GmbH
# SPDX-License-Identifier: MPL-2.0

name: ci-experimental
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'makefiles/**'
      - '.github/**'
      - '**/*.tm.hcl'
      - '.tool-versions'

jobs:
  build_test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: ["windows-2022"]
        go: ["1.20"]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: configure git
        run: git config --global core.autocrlf false

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: make test
        run: make test

      - name: make build
        run: make build
