# Copyright 2023 Terramate GmbH
# SPDX-License-Identifier: MPL-2.0

name: coverage report

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'makefiles/**'
      - '.github/**'
      - '**/*.tm.hcl'
      - '.tool-versions'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'makefiles/**'
      - '.github/**'
      - '**/*.tm.hcl'
      - '.tool-versions'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: generate and publish coverage
    env:
      COVERAGE_REPORT: coverage.txt

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: generate coverage report
        run: make coverage

      - name: upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          directory: .
          files: ${{env.COVERAGE_REPORT}}
          flags: tests
          name: codecov-umbrella
          verbose: true
